#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/8b3cad0692b6c58f827c0a9b35f1ad733547504b/modules/openapi-generator/src/main/resources/python

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/python"

docker run --rm \
  -v "${DIR}/:/local" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php" ./bin/generate-examples.php

printf "Install Python dependencies ...\n"
bash "${DIR}/bin/python" pip install -r requirements.txt

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

printf "Running tests ...\n"
bash "${DIR}/bin/python" python -m unittest discover tests

printf "Success!\n"
