#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/8b3cad0692b6c58f827c0a9b35f1ad733547504b/modules/openapi-generator/src/main/resources/python

set -e

WORKINGDIR="/app/python"

docker run --rm \
  -v "${PWD}/:/local" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/oas/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${PWD}/vendor"
bash "${PWD}/bin/php" composer install
printf "\n"

printf "Adding examples to /examples ...\n"
rm -f "${PWD}/examples/"*.py
cp -r "${PWD}/oas/examples/"*.py "${PWD}/examples/"

printf "Adding examples to Docs ...\n"
bash "${PWD}/bin/php" ./bin/generate-examples.php

printf "Install Python dependencies ...\n"
bash "${PWD}/bin/python" pip install -r requirements.txt

printf "Replacing strings ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/scan_for

printf "Running tests ...\n"
bash "${PWD}/bin/python" python -m unittest discover tests

printf "Success!\n"
